package com.seo.selenium.ui;

public class SeleniumConstants
{

  // custom attributes naming convention: data-st-element--modifier
  // dynamic_header.tpl
  public static final String kAttrMainMenuItem = "data-st-main-menu-item";
  public static final String kAttrMainMenuGoogle = kAttrMainMenuItem + "--google";
  public static final String kAttrMainMenuAnalytics = kAttrMainMenuItem + "--analytics";
  public static final String kAttrMainMenuHome = kAttrMainMenuItem + "--home";
  public static final String kAttrMainMenuReports = kAttrMainMenuItem + "--reports";
  public static final String kAttrMainMenuRanking = kAttrMainMenuItem + "--ranking";
  // top_navbar.tpl
  public static final String kAttrNavbarItem = "data-st-navbar-item";
  public static final String kAttrNavbarAccountDropdown = kAttrNavbarItem + "--account";
  public static final String kAttrDropdownItem = "data-st-dropdown-item";
  // users.tpl
  public static final String kAttrUserItem = "data-st-user-item";
  public static final String kAttrUserItemAdmin = kAttrUserItem + "--admin";
  public static final String kAttrUserItemTeam = kAttrUserItem + "--team";
  public static final String kAttrUserItemCustomer = kAttrUserItem + "--customer";
  public static final String kAttrUserItemEmail = kAttrUserItem + "-email";
  public static final String kAttrUserAccess = kAttrUserItem + "-access";
  //filter_menu.tpl
  public static final String kAttrList = "data-st-list";
  public static final String kAttrListUnstyled = kAttrList + "--unstyled";
  public static final String kAttrListUnstyledScrollable = kAttrListUnstyled + "--scrollable";
  // general
  public static final String kAttrCheckBox = "data-st-checkbox";
  // edit_subuser_projects.php, editacces.tpl
  public static final String kAttrCheckBoxWebsites = kAttrCheckBox + "--websites";
  public static final String kAttrWebsitesItem = "data-st-websites-item";

  // asserts
  public static final String kAssertAnalyticsAccount = "Analytics account: Atomic tangerine";
  public static final String kAssertAnalyticsProperty = "Analytics property: Ade Weebly Website Analytics";
  public static final String kAssertAnalyticsView = "Analytics view: adevitan.weebly.com";
  public static final String kAssertGoogleAccount = "Google account: seo.test@gmail.com";
  
  //attributes
  public static final String kAttributeChecked = "checked";
  public static final String kAttributeClass = "class";
  public static final String kAttributeDataSearchable = "data-searchable";
  public static final String kAttributeDiabled = "disabled";
  public static final String kAttributeExpandable = "expandable";
  public static final String kAttributeStyle = "style";
  public static final String kAttributeTitle = "title";
  public static final String kAttributeValue = "value";
  
  //classes
  public static final String kClassAccountEmail = "account-email";
  public static final String kClassActive = "active";
  public static final String kClassAlert = "alert";
  public static final String kClassBgTwitter = "bg-twitter";
  public static final String kClassBold = "bold";
  public static final String kClassBootbox = "bootbox";
  public static final String kClassBootboxInput = "bootbox-input";
  public static final String kClassBtn = "btn";
  public static final String kClassBtnGroup = "btn-group";
  public static final String kClassBtnSuccess = "btn-success";
  public static final String kClassCheckbox = "checkbox";
  public static final String kClassColLg6 = "col-lg-6";
  public static final String kClassColMd3 = "col-md-3";
  public static final String kClassColMd6 = "col-md-6";
  public static final String kClassColMd9 = "col-md-9";
  public static final String kClassContainerMain = "container-main";
  public static final String kClassDayBold = "day-bold";
  public static final String kClassDisabled = "disabled";
  public static final String kClassDivider = "divider";
  public static final String kClassDragulaNotDraggable = "dragula__not-draggable";
  public static final String kClassDropdown = "dropdown";
  public static final String kClassDropdownHeader = "dropdown-header";
  public static final String kClassDummyDataAction = "dummy-data__action";
  public static final String kClassDummyDataCover = "dummy-data__cover";
  public static final String kClassExpandable = "expandable";
  public static final String kClassExpander = "expander";
  public static final String kClassFormGroup = "form-group";
  public static final String kClassFrequencyOndemandBtn = "frequency-ondemand-btn";
  public static final String kClassGettingStarted = "getting-started";
  public static final String kClassGravatar = "gravatar";
  public static final String kClassHidden = "hidden";
  public static final String kClassIconChevronDown = "icon-chevron-down";
  public static final String kClassIconCog = "icon-cog";
  public static final String kClassIconEdit = "icon-edit";
  public static final String kClassIconFacebookSign = "icon-facebook-sign";
  public static final String kClassIconTwitterSign = "icon-twitter-sign";
  public static final String kClassLabelWarning = "label-warning";
  public static final String kClassLiSearchable = "li-searchable";
  public static final String kClassModalBody = "modal-body";
  public static final String kClassModalContent = "modal-content";
  public static final String kClassModalDialog = "modal-dialog";
  public static final String kClassModalFooter = "modal-footer";
  public static final String kClassMyChecks = "mychecks";
  public static final String kClassPrev = "prev";
  public static final String kClassRow = "row";
  public static final String kClassSelectedByDefault = "selected_by_default";
  public static final String kClassSelectedSesClass = "selectedsesclass";
  public static final String kClassSeleniumDropdown = "selenium_dropdown";
  public static final String kClassSortable = "sortable";
  public static final String kClassSwitch = "switch";
  public static final String kClassTablePagination = "table-pagination";
  public static final String kClassTableResponsive = "table-responsive";
  public static final String kClassTableStriped = "table-striped";
  public static final String kClassTrEven = "tr-even";
  public static final String kClassTrOdd = "tr-odd";
  public static final String kClassTrow = "trow";
  public static final String kClassVisible = "visible";
  public static final String kClassVisibleXs = "visible-xs";
  public static final String kClassWell = "well";
  public static final String kClassWhiterow = "whiterow";
  
  //credentials
  public static final String kCredentials = "credentials";
  public static final String kCredentialsLiveTest = "livetest";
  public static final String kCredentialsLocal = "local";
  public static final String kTesting = "testing";
  public static final String kTestingTrue = "true";
  
  //dates
  public static final String kDate13May2013 = "13 May, 2013";
  public static final String kDate20152206 = "2015-22-06";
  public static final String kDate26Feb2015 = "26 Feb, 2015";
  public static final String kDateApril2015 = "April 2015";
  public static final String kDateJuly2015 = "July 2015";
  public static final String kDateJune2015 = "June 2015";
  public static final String kDateMay132013 = "May 13, 2013";
  public static final String kDepth10Pages = "10 pages";
  public static final String kDepth5Pages = "5 pages";
  
  //frequencies
  public static final String kFrequencyDaily = "daily";
  public static final String kFrequencyOnDemand = "on demand";
  public static final String kFrequencyWeekly = "weekly";
  
  //gmail settings
  public static final String kGmailSmtp = "smtp.gmail.com";
  public static final String kGmailSmtpPort = "465";
  public static final String kTestSmtp = "testsmtp";
  // hosts
  // for testing on beta, change host
  public static final String kHostLocal = "http://localhost/";
  public static final String kHostDev = "http://dev2015141.awrcloud.com";
  public static final String kHostLive = "http://www.awrcloud.com";
  
  //ids
  public static final String kIdAddAliasBtn = "add_alias_btn_1";
  public static final String kIdAddCompetitorsForm = "add_competitors_form";
  public static final String kIdAddNew = "add_new";
  public static final String kIdAddNewBtn = "add_new_btn";
  public static final String kIdAddNewCompetitors = "add_new_competitors";
  public static final String kIdAddNewKeywords = "add_new_keywords";
  public static final String kIdAddNewNote = "add_new_note";
  public static final String kIdAddYourCompetitors = "add-your-competitors";
  public static final String kIdAddYourKeywords = "add-your-keywords";
  public static final String kIdAllow = "allow";
  public static final String kIdApplyFilters = "apply_filters";
  public static final String kIdApplySelection = "apply_selection";
  public static final String kIdAvgMonthlySrch = "ad_gms";
  public static final String kIdBtnHome = "btn_home";
  public static final String kIdBtnNext = "btn_next";
  public static final String kIdBtnPrevious = "btn_previous";
  public static final String kIdCNewPassword = "cnewpassword";
  public static final String kIdChartDiv = "chartDiv";
  public static final String kIdChartModClicksBtn = "chart_mod_clicks_btn";
  public static final String kIdChartModCostBtn = "chart_mod_cost_btn";
  public static final String kIdChartModKwsBtn = "chart_mod_kws_btn";
  public static final String kIdChartModVisBtn = "chart_mod_vis_btn";
  public static final String kIdCheckLink1 = "checkLink1";
  public static final String kIdClicksTab = "clicks_tab";
  public static final String kIdCntrTxtSearchField = "cntr_txt_search_field";
  public static final String kIdCommonKwsBtn = "common_kws_btn";
  public static final String kIdCompany = "company";
  public static final String kIdCompetitionBtn = "competition_btn";
  public static final String kIdCompetitors = "competitors";
  public static final String kIdCompetitorsComparisonLink = "competitors_comparison_link";
  public static final String kIdCompetition = "ad_competition";
  public static final String kIdCostTab = "cost_tab";
  public static final String kIdCountryDropdown = "country_dropdown";
  public static final String kIdCurrentSections = "current-sections";
  public static final String kIdCustomLocation = "custom_locations";
  public static final String kIdDataCounter = "data_counter";
  public static final String kIdDateFromatSelect = "date_format_select";
  public static final String kIdDelSel = "del_sel";
  public static final String kIdDeleteAnalyticsAccountId = "delete_analytics_account_id";
  public static final String kIdDeleteHeader = "delete_header";
  public static final String kIdDeleteSelected = "delete_selected_";
  public static final String kIdDeltaChangesValue = "deltaChanges";
  public static final String kIdDepth = "depth";
  public static final String kIdDldLabel = "dld_label";
  public static final String kIdDom = "dom";
  public static final String kIdDomainFrequency = "newfrequency";
  public static final String kIdDomainTitle = "newtitle";
  public static final String kIdDoneButton = "done_button";
  public static final String kIdDow = "dow";
  public static final String kIdDpstart = "dpstart";
  public static final String kIdDpstop = "dpstop";
  public static final String kIdDropActions = "drop_actions";
  public static final String kIdEditGroupForm = "editgroupform";
  public static final String kIdEditTag = "edit_tag";
  public static final String kIdEmail = "Email";
  public static final String kIdFaviconUrl = "favicon_url";
  public static final String kIdFbLike = "fb_likes";
  public static final String kIdFbNewLikes = "fb_new_likes";
  public static final String kIdFbPageName = "fb_page_name";
  public static final String kIdFilterActions = "filter-actions";
  public static final String kIdFilterBranded = "filter-branded";
  public static final String kIdFilterColDisplay = "_filter_col_display_d0f0";
  public static final String kIdFilterColDisplay1 = "_filter_col_display_1";
  public static final String kIdFilterColDisplay2 = "_filter_col_display_2";
  public static final String kIdFilterColDisplay3 = "_filter_col_display_3";
  public static final String kIdFilterOpCaret3 = "filter_op_caret_3";
  public static final String kIdFilterOpDisplay = "_filter_op_display_d0f0";
  public static final String kIdFilterOpDisplay1 = "_filter_op_display_1";
  public static final String kIdFilterOpDisplay2 = "_filter_op_display_2";
  public static final String kIdFilterTags = "filter-tags";
  public static final String kIdFilterVal = "_filter_val_d0f0";
  public static final String kIdFilterVal1 = "_filter_val_1";
  public static final String kIdFilterVal2 = "_filter_val_2";
  public static final String kIdFilterVal3 = "_filter_val_3";
  public static final String kIdFreq = "freq";
  public static final String kIdFrequency = "frequency";
  public static final String kIdGaAddAccount = "ga_add_account";
  public static final String kIdGaToggle = "ga_toggle";
  public static final String kIdGapToggle = "gap_toggle";
  public static final String kIdGaps = "gaps";
  public static final String kIdGawToggle = "gaw_toggle";
  public static final String kIdGenerateBtn = "generate_button";
  public static final String kIdGroupId = "group_id";
  public static final String kIdGroupName = "group_name";
  public static final String kIdHtmlLabel = "html_label";
  public static final String kIdInputEmail = "inputEmail1";
  public static final String kIdInputPassword = "inputPassword1";
  public static final String kIdKeywordGroupName = "keyword_group_name";
  public static final String kIdKeywords = "keywords";
  public static final String kIdKeywordsTable = "keywords_table";
  public static final String kIdKeywordsFilter = "keyword_filter";
  public static final String kIdKwsTab = "kws_tab";
  public static final String kIdLocation = "location";
  public static final String kIdLogoUrl = "logo_url";
  public static final String kIdMainFilter = "main_filter";
  public static final String kIdMainWebsiteSelect = "main_website_select";
  public static final String kIdManageBtn = "manage_btn";
  public static final String kIdManageDeletedSelected = "manage_delete_selected";
  public static final String kIdMoreFiltersBtn = "more_filters_btn";
  public static final String kIdNaddNewSearchengines = "nadd_new_searchengines";
  public static final String kIdNewAliasType = "new_alias_type";
  public static final String kIdNewCompetitors = "newcompetitors";
  public static final String kIdNewDomain = "newdomain";
  public static final String kIdNewGroup = "new_group";
  public static final String kIdNewKeywords = "newkeywords";
  public static final String kIdNewPassword = "newpassword";
  public static final String kIdNewProjectTitle = "new_project_title";
  public static final String kIdNewAlias = "new_alias_type";
  public static final String kIdNewAliasURL = "new_alias_name";
  public static final String kIdNewWebsite = "main_website_select";
  public static final String kIdNewReportsBtn = "new_reports_btn";
  public static final String kIdNewdepth = "newdepth";
  public static final String kIdNext = "next";
  public static final String kIdNoteDate = "note_date";
  public static final String kIdNoteDescriptionTxt = "note_description_txt";
  public static final String kIdNoteGroupId = "note_group_id";
  public static final String kIdNpSearchField = "np_cntr_txt_search_field";
  public static final String kIdOverallHeading = "overall_heading";
  public static final String kIdOverallLink = "overall_link";
  public static final String kIdPaidKpi = "paid_kpi";
  public static final String kIdPasswd = "Passwd";
  public static final String kIdPassword = "password";
  public static final String kIdPrjName = "prj_name";
  public static final String kIdProjectCompetitors = "project_competitors";
  public static final String kIdProjectFilter = "project_filter";
  public static final String kIdProjectsEmail = "projects_email";
  public static final String kIdQuickReportName = "quick_report_name";
  public static final String kIdRange1m = "range_1m";
  public static final String kIdRange1y = "range_1y";
  public static final String kIdRange2y = "range_2y";
  public static final String kIdRange6m = "range_6m";
  public static final String kIdRankingTable = "rankingtable";
  public static final String kIdReportName = "report_name";
  public static final String kIdReportsAllowSelect = "reports_allow_select";
  public static final String kIdResearchField = "research_field";
  public static final String kIdRunDldLabel = "run_dld_label";
  public static final String kIdSeKwsBtn = "se_kws_btn";
  public static final String kIdSearchKeywordToggler = "searchkeywordtoggler";
  public static final String kIdSearchengines = "searchengines";
  public static final String kIdSearchField = "searchfield";
  public static final String kIdSegroupsDropdown = "segroups_dropdown";
  public static final String kIdSelAddNewProject = "sel_add_new_project";
  public static final String kIdSelAddWebsiteBtn = "sel_add_website_btn";
  public static final String kIdSelAll = "sel_all";
  public static final String kIdSelAllCompetitors = "sel_all_comp";
  public static final String kIdSelAllHeader = "sel-all-header";
  public static final String kIdSelAllKws = "sel_all_kws";
  public static final String kIdSelAllSe = "sel_all_se";
  public static final String kIdSelCompName = "sel_comp_name";
  public static final String kIdSelFilterDisplay = "_sel_filter_display";
  public static final String kIdSelHeader = "sel_header";
  public static final String kIdSelKwDisplay = "_sel_kw_display";
  public static final String kIdSelMdDisplay = "_sel_md_display";
  public static final String kIdSelSeDisplay = "_sel_se_display";
  public static final String kIdSelWsDisplay = "_sel_ws_display";
  public static final String kIdSelectedCountryName = "country_dropdown";
//  public static final String kIdSelectedSegroupName = "selected_segroup_name";
  public static final String kIdSelectedSegroupName = "segroups_dropdown";

  public static final String kIdSelocationDropdown = "selocation_dropdown";
  public static final String kIdSesAddButton = "ses_add_button";
  public static final String kIdSignIn = "signIn";
  public static final String kIdSignupEmail = "signupemail";
  public static final String kIdSignupFirstname = "signupfirstname";
  public static final String kIdSignupPassword = "signuppassword";
  public static final String kIdSmtpCpassword = "smtp_cpassword";
  public static final String kIdSmtpEmail = "smtp_email";
  public static final String kIdSmtpName = "smtp_name";
  public static final String kIdSmtpPassword = "smtp_password";
  public static final String kIdSmtpPort = "smtp_port";
  public static final String kIdSmtpSecurity = "smtp_security";
  public static final String kIdSmtpServer = "smtp_server";
  public static final String kIdSmtpUsername = "smtp_username";
  public static final String kIdSubmitApproveAccess = "submit_approve_access";
  public static final String kIdTagActions = "tag_actions";
  public static final String kIdTagBadge = "tag_badge";
  public static final String kIdTagName = "tag_name";
  public static final String kIdTopSites = "top_sites";
  public static final String kIdTwFollowers = "tw_followers";
  public static final String kIdTwLists = "tw_lists";
  public static final String kIdTwScreenName = "tw_screen_name";
  public static final String kIdUsernameOrEmail = "username_or_email";
  public static final String kIdValidateButton = "validateButton";
  public static final String kIdViewDisplay = "view_display";
  public static final String kIdVisTab = "vis_tab";
  public static final String kIdWebsite = "website";
  public static final String kIdWebsite1 = "website1";
  public static final String kIdWebsite2 = "website2";
  
  //javascript commands
  public static final String kJSCommand = "return chartStartDate";
  
  //link text
  public static final String kLinkText1M = "1m";
  public static final String kLinkText6m = "6m";
  public static final String kLinkText7D = "7d";
  public static final String kLinkTextAccount = "Account";
  public static final String kLinkTextAccountSettings = "Account settings";
  public static final String kLinkTextActive = "Active";
  public static final String kLinkTextAdd = "Add";
  public static final String kTextAllWebsites = "All websites";
  public static final String kTextAnalytics = "Analytics";
  public static final String kLinkTextAddMoreSEs = "Add more search engines";
  public static final String kLinkTextAddNewTag = "Add new tag";
  public static final String kLinkTextAddTagWebsites = "Tag websites";
  public static final String kLinkTextAddSearchEngine = "Add more search engines";
  public static final String kLinkTextAddToTeam = "add to team";
  public static final String kLinkTextAdded = "Added";
  public static final String kLinkTextAds = "Ads";
  public static final String kLinkTextAll = "All";
  public static final String kLinkTextAllResults = "All Results";
  public static final String kLinkTextAllUrls = "All URLs";
  public static final String kLinkTextAlphabetically = "Alphabetically";
  public static final String kLinkTextArchdaily = "www.archdaily.com";
  public static final String kLinkTextAtomicTangerine = "atomic-tangerine";
  public static final String kLinkTextAtomicTangerine2 = "Atomic tangerine";
  public static final String kLinkTextAtomicTangerineCom = "atomic-tangerine.com";
  public static final String kLinkTextAtomicTangerinePhotography = "atomic-tangerine photography";
  public static final String kLinkTextAtomicTangerineWebsite = "Atomic tangerine Website Analytics";
  public static final String kLinkTextBestPosition = "Best position";
  public static final String kLinkTextBing = "Bing";
  public static final String kLinkTextBingRomania = "Bing Romania";
  public static final String kLinkTextBranded = "Branded";
  public static final String kLinkTextBrandedAndNonBranded = "Branded and Non-Branded";
  public static final String kLinkTextCPC = "CPC";
  public static final String kLinkTextChanged = "Changed";
  public static final String kLinkTextClicks = "Clicks";
  public static final String kLinkTextComfortable = "Comfortable";
  public static final String kLinkTextCommonKeywords = "Common keywords ";
  public static final String kLinkTextCompact = "Compact";
  public static final String kLinkTextCompetitors = "Competitors";
  public static final String kLinkTextCost = "Cost";
  public static final String kTextCrawling = "Crawling";
  public static final String kLinkTextCreate = "Create";
  public static final String kLinkTextCurrentWebsite = "Current website";
  public static final String kLinkTextDanger = "danger";
  public static final String kLinkTextDefault = "Default";
  public static final String kLinkTextDelete = "Delete";
  public static final String kLinkTextDeleteGroup = "Delete group";
  public static final String kLinkTextDeleteSelected = "Delete selected";
  public static final String kLinkTextDeleteTag = "Delete tag";
  public static final String kLinkTextDeleteWebsites = "Delete Websites";
  public static final String kLinkTextDemoteMember = "demote member";
  public static final String kLinkTextDeveloperAPI = "Developer API";
  public static final String kLinkTextDisallowResourcesHandling = "disallow resources handling";
  public static final String kLinkTextDownload = "Download";
  public static final String kLinkTextDropped = "Dropped";
  public static final String kLinkTextEqual = "Equal";
  public static final String kLinkTextExport = "Export";
  public static final String kLinkTextExportImport = "Export / Import";
  public static final String kLinkTextExtended = "Extended";
  public static final String kLinkTextFirstPlace = "First Place";
  public static final String kLinkTextGoogle = "Google";
  public static final String kLinkTextGoogleAnalytics = "Google Analytics";
  public static final String kTextGoogleAnalyticsData = "Google Analytics data";
  public static final String kLinkTextGoogleCustomLocation = "Google Custom Location";
  public static final String kLinkTextGoogleWebmasterTools = "Google Webmaster Tools";
  public static final String kLinkTextGreaterThan = "Greater than";
  public static final String kLinkTextImport = "Import";
  public static final String kLinkTextInactive = "Inactive";
  public static final String kLinkTextInviteUser = "Invite user";
  public static final String kLinkTextKeywords = "Keywords";
  public static final String kLinkTextLast4Updates = "Last 4 updates";
  public static final String kLinkTextLast7Updates = "Last 7 updates";
  public static final String kLinkTextLessThan = "Less than";
  public static final String kTextLinks = "Links";
  public static final String kLinkTextListWebsites = "List Websites";
  public static final String kLinkTextMGPhotographer = "mgphotographer";
  public static final String kLinkTextMGPhotographerCom = "mgphotographer.wordpress.com";
  public static final String kLinkTextMovedDown = "Moved Down";
  public static final String kLinkTextMovedUp = "Moved Up";
  public static final String kLinkTextMultipleDates = "Multiple dates";
  public static final String kLinkTextNewAccount = "New account";
  public static final String kLinkTextNonBranded = "Non-Branded";
  public static final String kLinkTextNone = "None";
  public static final String kLinkTextNotInTop10 = "Not in Top 10";
  public static final String kLinkTextNotRanked = "Not Ranked";
  public static final String kLinkTextOnDemand = "On Demand";
  public static final String kLinkTextOrganic = "Organic ";
  public static final String kLinkTextOther = "Other";
  public static final String kLinkTextOutOfTop10 = "Out of Top 10";
  public static final String kLinkTextPaid = "Paid";
  public static final String kLinkTextPhraseMatch = "Phrase match";
  public static final String kLinkTextPosition = "Position";
  public static final String kLinkTextPositions11To20 = "Positions 11 to 20";
  public static final String kLinkTextPositions4To10 = "Positions 4 to 10";
  public static final String kLinkTextPromote = "promote";
  public static final String kLinkTextQuickReport = "Quick Report";
  public static final String kLinkTextRanked = "Ranked";
  public static final String kLinkTextRelatedKeywords = "Related keywords";
  public static final String kLinkTextRemove = "Remove";
  public static final String kLinkTextReportNotification = "Report notification";
  public static final String klinkTextNewReportNotification = "New report notification";
  public static final String kLinkTextRomania = "Romania";
  public static final String kLinkTextSave = "Save";
  public static final String kLinkTextSaveTheNewConfiguration = "Save the new configuration";
  public static final String kLinkTextInviteClients = "Invite clients ";
  public static final String kLinkTextSaveWebsiteSettings = "Save website settings";
  public static final String kLinkTextScheduled = "Scheduled";
  public static final String kLinkTextSignOut = "Sign out";
  public static final String kLinkTextStartCrawl = "Start Crawl";
  public static final String kLinkTextSwitch = "Switch";
  public static final String kLinkTextTangerine = "tangerine";
  public static final String kLinkTextTop10 = "Top 10";
  public static final String kLinkTextTop3 = "Top 3";
  public static final String kLinkTextTop5 = "Top 5";
  public static final String kLinkTextTopPages = "Top pages";
  public static final String kLinkTextTopPositions = "Top Positions";
  public static final String kLinkTextTumblr = "tumblr";
  public static final String kLinkTextTumblrCom = "tumblr.com";
  public static final String kLinkTextTwitterAccount = "Twitter account";
  public static final String kLinkTextUniqueKeywords = "Unique keywords";
  public static final String kLinkTextUnread = "Unread";
  public static final String kLinkTextUpdate = "Update";
  public static final String kLinkTextUpgrade = "Upgrade";
  public static final String kLinkTextUrlOrTitle = "URL or Title";
  public static final String kLinkTextUsa = "USA";
  public static final String kLinkTextWebsiteAudit = "website audit";
  public static final String kLinkTextYahoo = "Yahoo";
  public static final String kLinkTextYahooRomania = "Yahoo Romania";
  public static final String kLinkTextAssignGroup = "Assign to new group";
  
  //names
  public static final String kNameAnalytics = "analytics";
  public static final String kNameBest = "best";
  public static final String kNameCompetition = "competition";
  public static final String kNameCostPerClick = "cost_per_click";
  public static final String kNameGlobalMSearches = "global_monthly_searches";
  public static final String kNamePage = "page";
  public static final String kNamePerPage = "perpage";
  public static final String kNamePosition = "position";
  public static final String kNameRememberMe = "remember_me";
  public static final String kNameReportingEmails = "reporting_emails";
  public static final String kNameSearchQuery = "searchquery";
  public static final String kNameSite = "site";
  public static final String kNameTotalAveragePosition = "total_average_position";
  public static final String kNameTotalCTR = "total_ctr";
  public static final String kNameTotalClicks = "total_clicks";
  public static final String kNameTotalImpressions = "total_impressions";
  public static final String kNameType = "type";
  
  //parameters
  public static final String kParameterActionManagerActiveCompetitors = "?action=manageproject&activetab=competitors";
  public static final String kParameterDomainRescuecomCom = "?domain=rescuecom.com";
  public static final String kParameterHref1 = "href=1";
  public static final String kParametersDomainEmptyHref1 = "?domain=&href=1";
  public static final String kParametersDomainHref = "?domain=&website1=&href=1";

  // project ids
  public static final String kProjectId1 = "?project_id=1";
  public static final String kProjectId11 = "?project_id=11";
  public static final String kProjectId114 = "?project_id=114";
  public static final String kProjectId115 = "?project_id=115";
  public static final String kProjectId139 = "?project_id=139";
  public static final String kProjectId19 = "?project_id=19";
  public static final String kProjectId2 = "?project_id=2";
  public static final String kProjectId267 = "?project_id=267";
  public static final String kProjectId287 = "?project_id=287";
  public static final String kProjectId32 = "?project_id=32";
  public static final String kProjectId321 = "?project_id=321";
  public static final String kProjectId50 = "?project_id=50";
  public static final String kProjectId89 = "?project_id=89";
  public static final String kProjectId25 = "?project_id=25";
  public static final String kProjectId30 = "?project_id=30";
  public static final String kProjectId31 = "?project_id=31";
  public static final String kProjectId33 = "?project_id=33";
  public static final String kProjectId35 = "?project_id=35";
  
  //project ids with other parameters
  public static final String kAndProjectId1 = "&project_id=1";
  public static final String kAndProjectId26 = "&project_id=26";;
  public static final String kAndProjectId33 = "&project_id=33";
  public static final String kAndProjectId287 = "&project_id=287";
  
  //tags
  public static final String kTagS = "s";
  public static final String kTagTable = "table";
  public static final String kTagTbody = "tbody";
  public static final String kTagTh = "th";
  
  //text
  public static final String kTextA = "A";
  public static final String kTextAcMilan = "Ac Milan";
  public static final String kTextAccount = "Account";
  public static final String kTextAccountSettings = "Account settings";
  public static final String kTextAdeVitan = "ade_vitan";
  public static final String kTextAddKeywords = "Information\n\n\n3 keywords have been successfully added";
  public static final String kTextAllKeywords = "All Keywords";
  public static final String kTextKeywordFilter = "advancedwebranking";
  public static final String kTextAllResult = "All Results";
  public static final String kTextAnalyticsDashboard = "Analytics Dashboard";
  public static final String kTextAtom = "Atom";
  public static final String kTextAtomicTangerine = "Atomic Tangerine";
  public static final String kTextAtomic_Tangerine = "atomic-tangerine.com";
  public static final String kTextAuthorizeGWT = "Authorize AWR Cloud to access data from Google Webmaster Tools.";
  public static final String kTextAverageRank = "Average Rank";
  public static final String kTextAvgPosition = "Avg Position";
  public static final String kTextBBC = "bbc.com";
  public static final String kTextBestPosition = "Best Position";
  public static final String kTextBlizzard = "Blizzard";
  public static final String kTextAWRAlias = "AWR Alias";
  public static final String kTextabcd = "abcd";
  public static final String kTextKeywordseo = "seo";
  public static final String kTextGroupSeo = "Seo group";
  public static final String kTextCreateNew = "Create your first report";
  public static final String kTextCPC = "CPC";
  public static final String kTextCTR = "CTR";
  public static final String kTextChange = "Change";
  public static final String kTextClickShare = "Click Share";
  public static final String kTextClicks = "Clicks";
  public static final String kTextComments = "Comments";
  public static final String kTextCompanyName1 = "Company Name 1";
  public static final String kTextCompanyName2 = "Company Name 2";
  public static final String kTextCompetition = "Competition";
  public static final String kTextCompetitorRank = "rankranger";
  public static final String kTextComputer = "computer";
  public static final String kTextConnectGWT = "Connect Google Webmaster Tools";
  public static final String kTextConnectGoogleAnalytics = "Connect Google Analytics";
  public static final String kTextCost = "Cost";
  public static final String kTextDelete = "Delete";
  public static final String kTextDeleteTag = "Delete tag";
  public static final String kTextDescriptionTest = "Description test";
  public static final String kTextDeveloperApiKey = "Your current developer API token:";
  public static final String kTextDropped = "Dropped";
  public static final String kTextEmag = "emag";
  public static final String kTextEstimatedVisits = "Estimated Visits";
  public static final String kTextFixnowUs = "fixnow.us";
  public static final String kTextFollowers = "FOLLOWERS";
  public static final String kTextG = "G";
  public static final String kTextGWTdata = "Google Webmaster Tools data";
  public static final String kTextGroupTest = "Group test";
  public static final String kTextGoogle = "Google";
  public static final String kTextHidden = "hidden";
  public static final String kTextHostname1 = "dragosdev.atomic-tangerine.com";
  public static final String kTextHostname2 = "dragosdev2.atomic-tangerine.com";
  public static final String kTextHostnameLive1 = "dragoslive.atomic-tangerine.com";
  public static final String kTextHostnameLive2 = "dragoslive2.atomic-tangerine.com";
  public static final String kTextImpressions = "Impressions";
  public static final String kTextKeyword = "Keyword";
  public static final String kTextKeywordEvolution = "Keyword Evolution";
  public static final String kTextKeywordGroup = "Keyword group";
  public static final String kTextKeywordRanking = "Keyword Ranking";
  public static final String kTextLastUpdate = "Last Update";
  public static final String kTextLikes = "LIKES";
  public static final String kTextLogo1 = "http://i.imgur.com/lqIAj.jpg";
  public static final String kTextLogo2 = "http://socktail.com/images/logo/g7719.png";
  public static final String kTextMyPhoneSupportCom = "myphonesupport.com";
  public static final String kTextMozCom = "moz.com";
  public static final String kTextName = "Name";
  public static final String kTextNewGroup = "New Group";
  public static final String kTextNewPassword = "testpassword";
  public static final String kTextNewtag = "newtag";
  public static final String kTextNewExport = "New export";
  public static final String kTextNoDataAvailableForWebsite = "No data available for the selected website" + "\n"
      + "No update has been performed for this website. To see fresh data from the search engines, you need to start or schedule an update from your Website list." + "\n"
      + "Go to Websites list";
  public static final String kTextNoDataToDisplay = "No data to display. There are no updates available in the selected chart range";
  public static final String kTextNoWebsitesMatching = "There are no websites matching your current website filter \"emag\"";
  public static final String kTextNoWebsitesMatching2 = "There are no websites matching your current website filter \"uefa\"";
  public static final String kTextNothing = "Nothing";
  public static final String kTextOk = "OK";
  public static final String kTextOnDemand = "on demand";
  public static final String kTextOrganicVisits = "Organic Visits";
  public static final String kTextPage = "Page";
  public static final String kTextPaid = "paid";
  public static final String kTextPhotography = "photography";
  public static final String kTextPlayground = "Playground";
  public static final String kTextPosition = "Position";
  public static final String kTextRankings = "Rankings";
  public static final String kTextRankingsOverview = "Rankings Overview";
  public static final String kTextRepair = "repair";
  public static final String kTextReport = "Test Report - Selenium";
  public static final String kTextReportNotification = "Report notification";
  public static final String kTextReports = "Reports";
  public static final String kTextRescuecom = "rescuecom";
  public static final String kTextRescuecomCom = "rescuecom.com";
  public static final String kTextResearch = "Research";
  public static final String kTextResults = "Results";
  public static final String kTextRomania = "Romania";
  public static final String kTextSettings = "Settings";
  public static final String kTextSMTPSuccessfull = "Your SMTP settings have been successfully tested.";
  public static final String kTextSSL = "SSL";
  public static final String kTextSearchEngineComparison = "Search Engine Comparison";
  public static final String kTextSearches = "Searches";
  public static final String kTextSerp = "SERP";
  public static final String kTextSettingsSavedSuccessfully = "Settings have been successfully updated.";
  public static final String kTextSignOut = "Sign out";
  public static final String kTextSocial = "Social";
  public static final String kTextSocialNoPerm = "Sorry! No social profiles connected. Please contact the AWR Cloud account owner.";
  public static final String kTextTa = "ta";
  public static final String kTextTagTest = "TagTest";
  public static final String kTextTeamTag = "TeamTag";
  public static final String kTextTest = "test";
  public static final String kTextUefa = "uefa";
  public static final String kTextTestKeywordGroups = "Test Keyword Groups";
  public static final String kTextTestKeywordRankings = "Test Keyword Rankings";
  public static final String kTextTestSECRankings = "Test SEC Rankings";
  public static final String kTextTestVisibilityRankings = "Test Visibility Rankings";
  public static final String kTextTestWebCompRankings = "Test WebComp Rankings";
  public static final String kTextTestWebRankings = "Test Web Rankings";
  public static final String kTextToFotoRo = "to-foto.ro";
  public static final String kTextTrend = "Trend";
  public static final String kTextUpdate = "Update";
  public static final String kTextUpdateTag = "Update tag";
  public static final String kTextUrl = "URL";
  public static final String kTextUrlOrTitle = "URL or Title";
  public static final String kTextValue1 = "1";
  public static final String kTextValue10 = "10";
  public static final String kTextVideoWrapperClass = "videoWrapper";
  public static final String kTextVisibility = "Visibility";
  public static final String kTextVisibilityPercent = "Visibility Percent";
  public static final String kTextVisibilityScore = "Visibility Score ";
  public static final String kTextVolume = "Volume";
  public static final String kTextWebsite = "Website";
  public static final String kTextWebsiteFixnowUs = "fixnow.us";
  public static final String kTextWebsiteRanking = "Website Ranking";
  public static final String kTextWebsiteRescuecomCom = "rescuecom.com";
  public static final String kTextWebsiteSettings = "Website settings";
  public static final String kTextWebsitesComparison = "Websites Comparison";
  public static final String kTextYes = "Yes";
  public static final String kTextg = "g";
  public static final String kTextssl = "ssl";
  
  //urls
  public static final String kUrlAccountSettings = "/profile.php";
  public static final String kUrlAnalyticsSettings = "/show_analytics_accounts.php";
  public static final String kUrlClickShare = "/reports_clickshare.php";
  public static final String kUrlCompetitorsSettings = "/projects.php";
  public static final String kUrlDevApi = "/dev-api.php";
  public static final String kUrlExports = "exports.php";
  public static final String kUrlFacebook = "/facebook.php";
  public static final String kUrlImports = "import.php";
  public static final String kUrlKeywordGroups = "/reports_keywordgroups.php";
  public static final String kUrlKeywordNotes = "/keywords_notes.php";
  public static final String kUrlKeywordRankings = "/reports_keyword_ranking.php";
  public static final String kUrlKeywordSettings = "/projects.php?action=manageproject&activetab=keywords";
  public static final String kUrlLogin = "/login.php";
  public static final String kUrlNewReportManager = "/newreportmanager.php";
  public static final String kUrlOrganicLandingPages = "/organic/landing-pages.php";
  public static final String kUrlOverview = "/overview_organic.php";
  public static final String kUrlOverviewAnalytics = "/dashboard_vis.php";
  public static final String kUrlOverviewKeywords = "/overview_keywords.php";
  public static final String kUrlOverviewOrganic = "/overview_organic.php";
  public static final String kUrlPaidAds = "paid/ads.php?";
  public static final String kUrlPaidLandingPages = "paid/landing-pages.php";
  public static final String kUrlPlaygroundKWsGWT = "/gwt_import.php";
  public static final String kUrlPlaygroundWebsiteAuditor = "/website-auditor.php";
  public static final String kUrlProfilePlans = "profile-plans.php";
  public static final String kUrlProfileWhitelabel = "/profile-whitelabel.php";
  public static final String kUrlProjectList = "/projects.php";
  public static final String kUrlProjectsPhp = "/projects.php";
  public static final String kUrlReports = "/reports.php";
  public static final String kUrlResearchCompetitorsIntersection = "/research/competitors-intersection.php";
  public static final String kUrlResearchDashboard = "/research/dashboard.php";
  public static final String kUrlResearchKeywords = "research/keywords";
  public static final String kUrlResearchKeywordsKeywords = "/research/keywords/keywords.php";
  public static final String kUrlResearchOrganicRankings = "/research/organic/rankings.php";
  public static final String kUrlResearchPaidRankings = "/research/paid/rankings.php";
  public static final String kUrlSearchEngineComparison = "/reports_overview_ranking.php";
  public static final String kUrlSearchengineSettings = "/projects.php?action=manageproject&activetab=searchengines";
  public static final String kUrlSeoBrowser = "/seo_browser.php";
  public static final String kUrlSignup = "/signup.php";
  public static final String kUrlSocial = "/social.php";
  public static final String kUrlSocialSettings = "/projects.php?action=manageproject&activetab=social";
  public static final String kUrlTwitter = "/twitter.php";
  public static final String kUrlUsers = "/users.php";
  public static final String kUrlVisibility = "/visibility.php";
  public static final String kUrlVisibilityComparison = kHostDev + "/rankingreports.php?action=showstats&activetab=stats&report_type=visibility";
  public static final String kUrlWebsiteAuditor = "/website-auditor.php";
  public static final String kUrlWebsiteComparison = "/reports_seoverview_ranking.php";
  public static final String kUrlWebsiteRankings = "/reports_website_ranking.php";
  public static final String kUrlWebsiteSettings = "/projects.php?action=manageproject&activetab=websitesettings";
  
  //user informations
  public static final String kUserAdeWeebly = "Ade Weebly Website";
  public static final String kUserAdeVitanWeebly = "adevitan.weebly.com";
  public static final String kUserAlias = "*.emag.ro";
  public static final String kUserAlias1 = "*.cinemagia.ro";
  public static final String kUserAlias2 = "*.sweden.se";
  public static final String kUserAWRAlias = "AWR Alias";
  public static final String kUserAWRAliasProject = "AWR Alias project";
  public static final String kUserAliasTypeRootDomain = "new_alias_type";
  public static final String kUserAnalyticsAccount = "seo.test@gmail.com";
  public static final String kUserAnalyticsPassword = "testseo3test";
  public static final String kUserAtomic = "Atomic";
  public static final String kUserAtomicTangerine = "Atomic Tangerine";
  public static final String kUserCompetitorAltex = "http://www.altex.ro/";
  public static final String kUserCompetitorAntena3 = "antena3.ro";
  public static final String kUserCompetitorPcgarage = "http://www.pcgarage.ro/";
  public static final String kUserCompetitorProTv = "www.protv.ro";
  public static final String kUserCompetitorRealitatea = "realitatea.net";
  public static final String kUserCompetitors = "altex.ro, pcgarage.ro";
  public static final String kUserContrySweden = "Sweden";
  public static final String kUserCountryRo = "RO";
  public static final String kUserCountryRomania = "Romania";
  public static final String kUserDomainName = "www.emag.ro/";
  public static final String kUserDomainName2 = "www.realitatea.net";
  public static final String kUserDomainName3 = "uefa.com";
  public static final String kUserDomainNameShorter = "emag.ro";
  public static final String kUserDomainNameShorter1 = "cinemagia.ro";
  public static final String kUserDomainNameShorter2 = "sweden.se";
  public static final String kUserDomainTitle = "emag.ro";
  public static final String kUserEmail0 = "dragosgeornoiu@gmail.com";
  public static final String kUserEmail1 = "firstlasttesting1@gmail.com";
  public static final String kUserEmail2 = "qa.awrcloud5@gmail.com";
  public static final String USER2_EMAIL = "qa.awrcloud5@gmail.com";
  public static final String kUserEmail3 = "alintest84@outlook.com";
  public static final String kUserEmail4 = "patrualin@gmail.com";
  public static final String kUserEmail5 = "alin_acc01@hotmail.com";
  public static final String kUserEmail6 = "alintest84@yahoo.com";
  public static final String kUserEmail7 = "alin_acc01@hotmail.com";
  public static final String kUserEmail8 = "ade@atomic-tangerine.com";
  public static final String kUserEmail9 = "qa.awrcloud@gmail.com";
  public static final String kUserEmailCustomer = "alin_acc04@hotmail.com";
  public static final String kUserFirstname = "Firstname Lastname";
  public static final String kUserFrequencyWeekly = "weekly";
  public static final String kUserGroupName = "test";
  public static final String kUserGroupNameUpdated = "testUpdated";
  public static final String kUserImgur = "imgur";
  public static final String kUserBlizzard = "Blizzard";
  public static final String kUserKeyword = "keyword";
  public static final String kUserNewProjectTitle1 = "abcd";
  public static final String kUserNewProjectTitle2 = "dcba";
  public static final String kUserNewProjTitle1 = "AWR Alias";
  public static final String kUserNewProjTitle2 = "AWR Alias project";
  public static final String kUserNewWebsite1 = "advancedwebranking.com";
  public static final String kUserNewWebsite2 = "moz.com";
  public static final String kUserNewAlias = "http://www.advancedwebranking.com/team";
  public static final String kUserNoOfPages5 = "5 pages";
  public static final String kUserPassword0 = "qwerty1234";
  public static final String kUserPassword1 = "qWeRtY1234";
  public static final String USER2_PASSWORD = "qWeRtY1234";
  public static final String kUserPassword2 = "ade11210";
  public static final String kUserPassword3 = "Password1";
  public static final String kUserPassword4 = "qWeRtY1234";
  public static final String kUserPassword5 = "Password1";
  public static final String kUserPassword6 = "Password1";
  public static final String kUserPassword7 = "Password1";
  public static final String kUserPassword8 = "ade11210";
  public static final String kUserPassword9 = "RUBaDUBaDUB@)!%";
  public static final String kUserPasswordCustomer = "Password1";
  public static final String kUserPasswordTeamNoPerm = "Password1";
  public static final String kUserPasswordTeamPerm = "Password1";
  public static final String kUserPasswordTeamNoPerm2 = "testpassword";
  public static final String kUserRealitatea = "Realitatea";
  public static final String kUserReportsEveryone = "Everyone";
  public static final String kUserSearchEngines = "Google, Yahoo Romania, Bing Romania";
  public static final String kUserTeamPerm = "alin_acc02@hotmail.com";
  public static final String kUserTeamNoPerm = "alin_acc03@hotmail.com";
  public static final String kUserTestAlias = "*.test.com";
  public static final String kUserTestAlias1 = "*.advancedwebranking.com";
  public static final String kUserTestAlias2 = "*.moz.com";
  public static final String kUserTwitterAccount = "testing12312131";
  public static final String kUserWebmasterAccount = "Account: ghitamircea@gmail.com";
  public static final String kUserWebmasterWebsite = "Connected website: http://www.atomic-tangerine.com/";
  public static final String kUserWebsiteAlias = "*.website.ro";
  public static final String kUserWebsiteKWs = "6 KWs";
  public static final String kUserWebsiteKWs1 = "10 KWs";
  public static final String kUserWebsiteKWs2 = "8 KWs";
  public static final String kUserWebsitePages = "5 pages";
  public static final String kUserWebsitePages1 = "10 pages";
  public static final String kUserWebsiteSes = "3 SEs";
  public static final String kUserWebsiteSes1 = "5 SEs";
  
  // string values
  public static final String kValue0 = "0";
  public static final String kValue1 = "1";
  public static final String kValue10 = "10";
  public static final String kValue100 = "100";
  public static final String kValue22 = "22";
  public static final String kValue25 = "25";
  public static final String kValue50 = "50";
  public static final String kValueMonday = "Monday";
  public static final String kValueMonthly = "monthly";
  public static final String kValueWeekly = "weekly";

  // array values
  public static final String[] kUserCompetitorsArray = { "CEL.ro", "http://www.evomag.ro/", "http://www.f64.ro/", "http://www.marketonline.ro/", "http://www.pcfun.ro/",
      "http://www.azerty.ro/", "http://www.mediadot.ro/", "http://www.pcmag.com/", "http://www.computerworld.com/", "http://www.oktal.ro/", "http://www.pcworld.com/",
      " http://www.amazon.com/" };
  public static final String[] kUserKeywordsArray = { "latpop", "telefon", "Samsung", "Apple", "s4", "s5", "desktop", "periferice", "electrocasnice" };
  public static final String[] kUserKeywordsArray1 = { "filme", "thor", "james bond", "box office", "hollywood", "spielberg", "tom hanks", "avengers", "oscars", "pierce brosnan" };
  public static final String[] kUserKeywordsArray2 = { "swede", "sweden.se", "swedish food", "nordic countries", "vikings", "what to do in sweden", "learning swedish",
      "capital of sweden" };
  public static final String[] kUserKeywordsArray3 = { "telegraph", "uk news", "news", "the telegraph", "london news", "united kingdom", "premier league" };
  public static final String[] kUserKeywordsArray4 = { "advancedwebranking", "advancedwebranking desktop", "advancedwebranking cloud" };
  public static final String[] kUserCustomLocations = { "5th avenue", "los angeles", "boston" };
  public static final String[] kUserCompetitorsArray2 = { "rankranger.com", "https://www.facebook.com/RankRangerSEO" };
  
  //int values
  public static final int kNumberOfKeywords = 6;
  public static final int kNumberOfKeywords1 = 10;
  public static final int kNumberOfKeywords2 = 8;
  public static final int kSettingsNoOfSecitons = 11;

  /**
   * TODO comment this method's body when testing locally, on windows. our ec2
   * jenkins needs this to run.
   */
  public static void SetFirefoxBinaryPath()
  {
    // System.setProperty("webdriver.firefox.bin",
    // "/usr/local/firefox/firefox");
  }

  public static void kTextCreateNew()
  {
    // TODO Auto-generated method stub

  }

}